name: Workflow

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assert-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.6.1

      - name: Install self
        run: pip install ./

      - name: Assert version matches tag
        run: test ${ pip show gha-poetry | grep Version | cut -d ' ' -f 2 } == ${{ github.ref_name }}
